#Intalling on CentOS
#https://github.com/Altinity/clickhouse-rpm-install

- name: Uninstall by YUM | Remove Clickhouse
  yum:
    name: "{{ item }}"
    purge: yes
    state: absent
  with_items: "{{ clickhouse_package }}"
  become: true

- name: Remove clickhouse config,data and logs
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  become: true
  when: clickhouse_remove_full|bool == True
